# Generated by Django 2.0.2 on 2018-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'table_nat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablenat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tablenat',
            name='ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tablenat',
            name='port',
            field=models.IntegerField(),
        ),
    ]
